#pragma once

#include "driver/spi_master.h"

#define TYPEWRT_SPI_HOST SPI2_HOST

#define TYPEWRT_PIN_SPI_MOSI 35
#define TYPEWRT_PIN_SPI_MISO 37
#define TYPEWRT_PIN_SPI_CLK  36
#define TYPEWRT_PIN_DISPLAY_CS 38
#define TYPEWRT_PIN_SD_CS 33
#define TYPEWRT_PIN_RTC_SDA 8
#define TYPEWRT_PIN_RTC_SCL 9
#define TYPEWRT_PIN_BLUE_LED 13
#define TYPEWRT_PIN_LIGHT_SENSOR 4
#define TYPEWRT_PIN_RGB_LED_DATA 40

#define TYPEWRT_PIN_LDO2_EN 39
#define TYPEWRT_PIN_LEDN 17
#define TYPEWRT_PIN_RST_EN 18
#define TYPEWRT_PIN_5V_EN 34
#define TYPEWRT_PIN_UART_TX 43
#define TYPEWRT_PIN_UART_RX 44

#define TYPEWRT_PIN_KBD_IO7  1
#define TYPEWRT_PIN_KBD_IO6  7
#define TYPEWRT_PIN_KBD_IO5 10
#define TYPEWRT_PIN_KBD_IO4 11
#define TYPEWRT_PIN_KBD_IO3  5
#define TYPEWRT_PIN_KBD_IO2  6
#define TYPEWRT_PIN_KBD_IO1 12
#define TYPEWRT_PIN_KBD_IO0 14
#define TYPEWRT_PIN_KBD_OE 16
#define TYPEWRT_PIN_KBD_LE 15

#define TYPEWRT_DISPLAY_WIDTH 320
#define TYPEWRT_DISPLAY_HEIGHT 240
#define TYPEWRT_FONT_HEIGHT 16
#define TYPEWRT_REFRESH_FULL_DISPLAY 0

#define TYPEWRT_ENABLE_LIGHT_SLEEP 1
#define TYPEWRT_LIGHT_SLEEP_IDLE_MS 1000

#define TYPEWRT_SD_MOUNT_POINT "/sdcard"
